# syntax=docker.io/docker/dockerfile:1

FROM node:22-alpine  AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json pnpm-lock.yaml* .npmrc* ./
RUN corepack enable pnpm && pnpm i;

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY src/ ./src
COPY public/ ./public
COPY next.config.ts ./
COPY hero.ts ./
COPY components.json ./
COPY tsconfig.json ./
COPY postcss.config.mjs ./
COPY package.json  package.json
COPY pnpm-lock.yaml pnpm-lock.yaml
COPY .npmrc .npmrc
COPY .env .env

RUN corepack enable pnpm && pnpm run build

FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

COPY --from=builder /app/public ./public

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static


USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOST=0.0.0.0

CMD ["node", "server.js"]